name: Feedback Issue
description: Feedback issues are used to gather feedback, suggestions, and experiences from users while iterating on a specific product feature.
title: "Feedback Issue: "
labels: ["feedback-issue"]
body:
- type: markdown
  attributes:
    value: Before raising a feedback issue, please search for [existing feedback issues](https://github.com/gitpod-io/gitpod/issues?q=is%3Aopen+is%3Aissue+label%3Afeedback-issue) to avoid creating duplicates. If you are looking to [report a bug](https://github.com/gitpod-io/gitpod/issues/new?assignees=&labels=type%3A+bug&template=bug_report.yml) or [suggest a feature request](https://github.com/gitpod-io/gitpod/issues/new?assignees=&labels=&template=feature_request.md&title=) choose a different issue template.
- type: textarea
  id: objective
  attributes:
    label: Objective
    description: Include the objective of this issue and any relevant features
  validations:
    required: true
